name: CI CD pipeline

on:
  push:
    branches: [ "CI-CD" ]
    pull_request:
      branches: [ "sanjeev-deployment" ]


jobs:

  test:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout code
        use: actions/checkout@v3

      - name: Setup JDK 17
        use: actions/checkout@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: run test using gradle
        use:  gradle/gradle-build-action@v2
        arguments:
          test




  build:
    # needs: test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: build shadownJar using gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: shadowJar

      - name: Archive shadowJar
        uses: actions/upload-artifact@v3
        with:
          name: esopApp
          path: build/libs

